### ISSUE TITLE
GeoMesa Configuration Service optional tableName

### ISSUE THREAD

**Issue by aheyne** [geomesa/geomesa-nifi#14]
It would be nice if the tableName property of the configuration service was not required. That way a configuration could be used across multiple tables and just store connection and login info. Ideally, if the processor has a table name, that takes precedent, then if no table name is available in the processor, use the one in the configuration service.

**Comment by elahrvivaz** [comment]
@aheyne feel free to open this as a JIRA ticket if you're still interested.
