### ISSUE TITLE
Errors from records not converting do not get to the UI

### ISSUE THREAD

**Issue by emilyselwood** [geomesa/geomesa-nifi#20]
If a date format is defined in a simple feature and the incoming records do not decode nothing makes it back to the UI with the errors. The only place they show up is in the nifi-app.log

**Comment by elahrvivaz** [comment]
There are two options here: 1) configure your converter or the processor as 'raise-errors' - this will cause the entire file to fail. 2) check the attribute `geomesa.ingest.failures` on the output flowfile and handle it as desired.
