### ISSUE TITLE
kafka missing from the geomesa-nifi-processors pom

### ISSUE THREAD

**Issue by wselwood** [geomesa/geomesa-nifi#21]
causes the com.101tec.zkclient jar to be missing from the nar which causes a class not found at runtime when trying to use it.

PR will follow shortly

**Comment by wselwood** [comment]
This should be resolved by #22

**Comment by jahhulbert-ccri** [comment]
Hi @wselwood I'm going to peek really quick to see why my existing kafka processors work without it.
