### ISSUE TITLE
Load conf from jar in lib

### ISSUE THREAD

**Issue by jahhulbert-ccri** [geomesa/geomesa-nifi#31]
* Properly load SFT and Converter conf plus transformers from jar file in lib dir
* Document properly how this works.

**Comment by wselwood** [comment]
From my experiments it does work as long as it is in a jar in the lib folder.  I was trying to keep the SFT and Converter spec in the nar that was creating the data so there was only one thing to deploy to the servers. Mostly my comment was making sure the documentation makes it clear it has to be a jar and not a nar due to the way the nifi classloaders work.

**Comment by jnh5y** [comment]
@jahhulbert-ccri any updates on this issue?

**Comment by jahhulbert-ccri** [comment]
not at the moment. likely best to add a geomesa ticket too.

**Comment by transdz** [comment]
How can i add my SFTS to the processor I tried the way provided in documentation but it's not working

**Comment by jahhulbert-ccri** [comment]
@transdz currently there are a few ways:
1. Repackage the nar with your SFTs in side (if your SFTs are in a jar)
2. Copy/paste them into the nifi processor config as typesafe config format
3. Create/use another SFT provider implementation other than the Classpath sft provider (https://www.geomesa.org/documentation/user/convert/usage_runtime.html) however at the moment i think you'd still have to package it in the nar file.

Are your SFTs in typesafe config or in java only?

**Comment by transdz** [comment]
thanks for  your fast reply @jahhulbert-ccri  
My SFT are in typesafe config format. i tried packaging them in a jar and copy it to the lib folder of Nifi but it wasn't reconized . can you help me and give steps to follow to add them

**Comment by jahhulbert-ccri** [comment]
![nifi](https://user-images.githubusercontent.com/7433591/47026420-630af580-d133-11e8-83e4-e71357f6b9c5.png)

All you need to do is paste the properties block in the image...sft conf for the sft and converter conf for the Converter.

You can test this with the example csv ones from geomesa: https://raw.githubusercontent.com/locationtech/geomesa/master/geomesa-tools/examples/ingest/csv/example.conf

Note you can only have one sft and one converter and they need to be nested in ```geomesa.sfts.<name>``` and ```geomesa.converters.<name>``` paths correction in config:

```
geomesa {
  sfts {
    "example-csv" = {
      attributes = [
        { name = "fid",      type = "Integer",         index = false                             }
        { name = "name",     type = "String",          index = true                              }
        { name = "age",      type = "Integer",         index = false                             }
        { name = "lastseen", type = "Date",            index = false                             }
        { name = "geom",     type = "Point",           index = true, srid = 4326, default = true }
      ]
    }
  }
}
```
the conf:
```
geomesa {
  converters {
    "example-csv" {
      type   = "delimited-text",
      format = "CSV",
      options {
        skip-lines = 1
      },
      id-field = "toString($fid)",
      fields = [
        { name = "fid",      transform = "$1::int"                     }
        { name = "name",     transform = "$2::string"                  }
        { name = "age",      transform = "$3::int"                     }
        { name = "lastseen", transform = "date('yyyy-MM-dd', $4)"      }
        { name = "lon",      transform = "$7::double"                  }
        { name = "lat",      transform = "$8::double"                  }
        { name = "geom",     transform = "point($lon, $lat)"           }
      ]
    }
  }
}
```

Then you can pass through the csv data:
```
ID,Name,Age,LastSeen,Friends,Skills,Lon,Lat,Vis
23623,Harry,20,2015-05-06,"Will, Mark, Suzan","patronus->10,expelliarmus->9",-100.2365,23,user
26236,Hermione,25,2015-06-07,"Edward, Bill, Harry","accio->10",40.232,-53.2356,user
3233,Severus,30,2015-10-23,"Tom, Riddle, Voldemort","potions->10",3,-62.23,user&admin
```

**Comment by transdz** [comment]
I tried as mentioned and the table was created but the data wasn't inserted 
![image](https://user-images.githubusercontent.com/17753238/47040797-7f388200-d187-11e8-9200-2a9ff16183e5.png)

**Comment by transdz** [comment]
The SftsName can't be set manualy , maybe is that the problem

**Comment by jahhulbert-ccri** [comment]
ahhh... It might be this: https://www.geomesa.org/documentation/user/accumulo/data_management.html#table-sharing

**Comment by jahhulbert-ccri** [comment]
So by default table sharing is true. if you scan the metadata table (nifitable) it will have info in it for your SFT. You can delete/drop it with the tools. But you can edit your SFT typesafe config like this:

https://github.com/locationtech/geomesa/blob/master/geomesa-tools/conf/sfts/tdrive/reference.conf#L10-L12

**Comment by transdz** [comment]
@jahhulbert-ccri  I think the problem is in the SftsName as i know you can't insert data in geomesa without SftsName event if you defined the simplefeatureType 
![image](https://user-images.githubusercontent.com/17753238/47042231-0affdd80-d18b-11e8-8175-c401d88188d9.png)

**Comment by elahrvivaz** [comment]
you can now point to jars containing converter definitions using the `ExtraClasspaths` property without bundling them into your nar or nifi lib dir.
